
name: Lint

on: pull_request

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Install ESLint
        run: |
          npm install eslint
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: | 
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}
      - name: Install Dependencies
        run: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          CI: true
      - name: ESLint action 
        uses: hallee/eslint-action@1.0.3
        # GITHUB_TOKEN in forked repositories is read-only
        # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }} 
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
